### ISSUE TITLE
Review #1 - Muy buen app!

### ISSUE THREAD

**Issue by FacundoEG** [Lio-n/dwf-m5-desafio#1]
Hola Lio-n! como estas? primero que todo te felicito por haber terminado el desafío!

La verdad que probé el juego en modo mobile y desktop, ambos funcionan muy bien y la responsividad aguanta hasta iphone 6.

Así que por mi parte LGTM! a mi parecer quedo muy bien todo!

Te mando un abrazo y nos vemos en el próximo modulo!

**Comment by Lio-n** [comment]
Hola FacundoEG!.

Gracias por tu comentario, me re animo. 

Estoy muy emocionado por el siguiente modulo!
